all:
	@rm -rf dist/;
	@mkdir -p dist/css;
	@mkdir -p dist/img;
	@mkdir -p dist/js;
	@cp index.html dist/;
	@cp css/*.css dist/css/;
	@cp -r css/themes dist/css/;
	@cp js/*.js dist/js/;
	@cp img/*.* dist/img/ || :;
